name: Build and Test

on:
  push:
    branches: [ ci23 ]
  pull_request:
    branches: [ ci23 ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: show Ubuntu version
      run: cat /etc/os-release | grep PRETTY_NAME | awk -F '=' '{print $2}'
    - name: update build environment
      run: sudo apt-get update --fix-missing -y && sudo apt-get upgrade --fix-missing -y
    - name: install prerequisites
      run: sudo apt-get install -y avahi-daemon libavahi-client-dev libssl-dev libpam-dev libusb-1.0-0-dev zlib1g-dev
    - name: configure
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer
    - name: make
      run: make
    - name: test
      run: make test || cat test/error_log*
